//
// Created by Gerwa on 2017/11/7.
//

#ifndef WHOSEEXCAVATORTECHNOLOGYADVANCED_QUERYSELECTOR_H
#define WHOSEEXCAVATORTECHNOLOGYADVANCED_QUERYSELECTOR_H


class QuerySelector {

};


#endif //WHOSEEXCAVATORTECHNOLOGYADVANCED_QUERYSELECTOR_H
